name: "PR workflow workaround"

permissions:
  issues: write

on: 
  workflow_dispatch:
  pull_request:
    types: [opened, labeled]
jobs:
  uploading-labels:
      runs-on: ubuntu-latest
      steps:
        - name: 
          id: up-labels
          env: 
            LABEL: ${{ github.event.label.name }}
          run: |
            mkdir -p ./label
            echo $LABEL > ./label/label
            echo $LABEL
        - uses: actions/upload-artifact@v4
          with:
            name: label
            path: label/
    