name: 'Trigger Workflow Test'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:

    - name: Generate Token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.WORKFLOW_APP_ID }}  
        private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: "dhinz_playground,datavault4dbt-ci-cd"
      
    - name: Call Workflow
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/ScalefreeCOM/datavault4dbt-ci-cd/actions/workflows/remote-test-endpoint.yml/dispatches \
        -f "ref=main"